# Generated by Django 5.0.2 on 2024-03-29 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=32)),
                ('title1', models.CharField(max_length=128)),
                ('title2', models.CharField(max_length=128)),
                ('title3', models.CharField(max_length=128)),
                ('text1', models.CharField(max_length=65536)),
                ('text2', models.CharField(max_length=65536)),
                ('text3', models.CharField(max_length=65536)),
            ],
        ),
    ]
