# Generated by Django 5.0.2 on 2024-03-29 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=32)),
                ('title', models.CharField(max_length=128)),
                ('text', models.CharField(max_length=65536)),
            ],
        ),
        migrations.CreateModel(
            name='News2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=32)),
                ('title', models.CharField(max_length=128)),
                ('text', models.CharField(max_length=65536)),
            ],
        ),
        migrations.CreateModel(
            name='News3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=32)),
                ('title', models.CharField(max_length=128)),
                ('text', models.CharField(max_length=65536)),
            ],
        ),
        migrations.DeleteModel(
            name='News',
        ),
    ]
