# Generated by Django 5.0.2 on 2024-03-30 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_news1_text_alter_news1_title_alter_news2_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news1',
            name='text',
            field=models.TextField(blank=True, max_length=65536, null=True),
        ),
        migrations.AlterField(
            model_name='news1',
            name='title',
            field=models.TextField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='news2',
            name='text',
            field=models.TextField(blank=True, max_length=65536, null=True),
        ),
        migrations.AlterField(
            model_name='news2',
            name='title',
            field=models.TextField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='news3',
            name='text',
            field=models.TextField(blank=True, max_length=65536, null=True),
        ),
        migrations.AlterField(
            model_name='news3',
            name='title',
            field=models.TextField(blank=True, max_length=128, null=True),
        ),
    ]
